name: voyagesdk_dart
description: SDK for creating software that interface with Packbase and other *base projects.
version: 0.1.0
repository: https://github.com/Wolfbite-Labs/voyagesdk-dart

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
