name: voyagesdk_dart
description: SDK for creating software that interface with Packbase and other *base projects.
version: 0.0.1
repository: https://github.com/Wolfbite-Labs/voyagesdk-dart

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  supabase: ^2.6.2
  #convert: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
